# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cokluKayit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_cokluKayit(object):
    def setupUi(self, Form_cokluKayit):
        Form_cokluKayit.setObjectName("Form_cokluKayit")
        Form_cokluKayit.resize(712, 403)
        Form_cokluKayit.setMinimumSize(QtCore.QSize(270, 50))
        Form_cokluKayit.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form_cokluKayit)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_excelleVeriGirisi = QtWidgets.QLabel(Form_cokluKayit)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_excelleVeriGirisi.setFont(font)
        self.label_excelleVeriGirisi.setStyleSheet("color: white;")
        self.label_excelleVeriGirisi.setObjectName("label_excelleVeriGirisi")
        self.verticalLayout_2.addWidget(self.label_excelleVeriGirisi)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pushButton_dosyaSec = QtWidgets.QPushButton(Form_cokluKayit)
        self.pushButton_dosyaSec.setMinimumSize(QtCore.QSize(400, 70))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dosyaSec.setFont(font)
        self.pushButton_dosyaSec.setStyleSheet("background-color: #2196F3;\n"
"color: black;\n"
"border-radius: 8px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_dosyaSec.setObjectName("pushButton_dosyaSec")
        self.verticalLayout_2.addWidget(self.pushButton_dosyaSec)
        self.pushButton_geri = QtWidgets.QPushButton(Form_cokluKayit)
        self.pushButton_geri.setMinimumSize(QtCore.QSize(400, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_geri.setFont(font)
        self.pushButton_geri.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 8px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_geri.setObjectName("pushButton_geri")
        self.verticalLayout_2.addWidget(self.pushButton_geri)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)

        self.retranslateUi(Form_cokluKayit)
        QtCore.QMetaObject.connectSlotsByName(Form_cokluKayit)

    def retranslateUi(self, Form_cokluKayit):
        _translate = QtCore.QCoreApplication.translate
        Form_cokluKayit.setWindowTitle(_translate("Form_cokluKayit", "Çoklu Kayıt"))
        self.label_excelleVeriGirisi.setText(_translate("Form_cokluKayit", "Excel ile Veri Girişi"))
        self.pushButton_dosyaSec.setText(_translate("Form_cokluKayit", "Dosya Seç"))
        self.pushButton_geri.setText(_translate("Form_cokluKayit", "Geri"))
