# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'girisEkrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GirisEkrani(object):
    def setupUi(self, GirisEkrani):
        GirisEkrani.setObjectName("GirisEkrani")
        GirisEkrani.resize(777, 496)
        GirisEkrani.setMinimumSize(QtCore.QSize(600, 400))
        GirisEkrani.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(GirisEkrani)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: white;")
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_tekliKayit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tekliKayit.setMinimumSize(QtCore.QSize(270, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_tekliKayit.setFont(font)
        self.pushButton_tekliKayit.setStyleSheet("background-color: #4CAF50;\n"
"color: black;\n"
"border-radius: 8px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_tekliKayit.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_tekliKayit.setObjectName("pushButton_tekliKayit")
        self.verticalLayout.addWidget(self.pushButton_tekliKayit)
        self.pushButton_cokluKayit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cokluKayit.setMinimumSize(QtCore.QSize(270, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cokluKayit.setFont(font)
        self.pushButton_cokluKayit.setStyleSheet("background-color: #2196F3;\n"
"color: black;\n"
"border-radius: 8px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_cokluKayit.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_cokluKayit.setObjectName("pushButton_cokluKayit")
        self.verticalLayout.addWidget(self.pushButton_cokluKayit)
        self.pushButton_kayitlar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kayitlar.setMinimumSize(QtCore.QSize(270, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_kayitlar.setFont(font)
        self.pushButton_kayitlar.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border-radius: 8px;\n"
"font-weight: bold;\n"
"")
        self.pushButton_kayitlar.setObjectName("pushButton_kayitlar")
        self.verticalLayout.addWidget(self.pushButton_kayitlar)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        GirisEkrani.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GirisEkrani)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 26))
        self.menubar.setObjectName("menubar")
        GirisEkrani.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GirisEkrani)
        self.statusbar.setObjectName("statusbar")
        GirisEkrani.setStatusBar(self.statusbar)

        self.retranslateUi(GirisEkrani)
        QtCore.QMetaObject.connectSlotsByName(GirisEkrani)

    def retranslateUi(self, GirisEkrani):
        _translate = QtCore.QCoreApplication.translate
        GirisEkrani.setWindowTitle(_translate("GirisEkrani", "Hoş Geldiniz!"))
        self.label_1.setText(_translate("GirisEkrani", "Veri Yönetim Uygulamanız!"))
        self.label_2.setText(_translate("GirisEkrani", "Kolay Veri Girişi ve Yükleme Seçenekleriyle Kişi Verilerinizi Düzenleyin."))
        self.pushButton_tekliKayit.setText(_translate("GirisEkrani", "Tekli Kayıt"))
        self.pushButton_cokluKayit.setText(_translate("GirisEkrani", "Çoklu Kayıt"))
        self.pushButton_kayitlar.setText(_translate("GirisEkrani", "Kayıtlar"))
